name: CCEssentails
version: 1.0
main: de.chrispe.main.Main
author: ChrisPE

commands:
   gm0:
   gms:
   gamemode0:
   gm1:
   gmc:
   gamemode1:
   gm2:
   gma:
   gamemode2:
   gm3:
   gmsp:
   gamemode3:
   heal:
   setspawn:
   spawn:
   invsee:
   ec: